### ISSUE TITLE
신고 기능에서 필요한 쿼리 구현

### ISSUE THREAD

**Issue by heemin88** [team-dotori/Guidely_Backend#14]
## Description

user Id로 신고 내역 조회와 같은 신고 기능에서 필요한 쿼리 구현.

## Todo
* [x] Location Repository, Dto 생성
* [x] 위도,경도로 위치 조회
* [x] 위치Id로 신고 List 조회 
* [x] User와 신고의 1대 다 관계성 추가
* [x] User Id로 Location 참조 기능 

## Etc
더 필요한 기능이 있다면 추가 예정

**Comment by heemin88** [comment]
신고 API 완료
